<?php
declare(strict_types=1);

/**
 * Minimal CLI demo: ask Saqr a question from the command line.
 *
 * Usage:
 *   php examples/cli.php "What is NCA ECC?"
 *   php examples/cli.php "ما هو نظام حماية البيانات الشخصية؟"
 *
 * If SAQR_ANTHROPIC_KEY (or ANTHROPIC_API_KEY) is set in the environment,
 * the response is generated by Claude Haiku using the retrieved sources.
 * Otherwise the top-ranked corpus entry is returned verbatim.
 */

require __DIR__ . '/../vendor/autoload.php';

if ($argc < 2) {
    fwrite(STDERR, "Usage: php {$argv[0]} \"<question>\"\n");
    exit(64);
}

$question = $argv[1];
$corpusPath = __DIR__ . '/../corpus/frameworks.json';

$corpus = \Saqr\Corpus::loadFromFile($corpusPath);
$pipeline = new \Saqr\Pipeline($corpus);

$result = $pipeline->ask($question, 'cli-' . get_current_user());

if (!$result['ok']) {
    fwrite(STDERR, "Error: {$result['reason']}\n");
    exit(1);
}

if ($result['reason'] === 'no_match') {
    echo "No corpus match for that question.\n";
    echo "Supported topics: NCA, SAMA, CST, Aramco, PDPL, ISO 27001.\n";
    exit(0);
}

echo "─── Answer " . ($result['used_llm'] ? "(LLM-generated)" : "(corpus verbatim)") . " ───\n\n";
echo strip_tags($result['answer'] ?? '', '<strong><em>') . "\n\n";

echo "─── Top-" . count($result['top']) . " retrieved sources ───\n";
foreach ($result['top'] as $i => $entry) {
    $idx = $i + 1;
    $cat = $entry['category'] ?? 'unknown';
    $kw  = implode(', ', array_slice($entry['keywords'], 0, 3));
    echo "  [{$idx}] {$cat} — keywords: {$kw}\n";
}
